[package]
name = "headshot"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
opencv = "0.94.2"
clap = { version = "4.1", features = ["derive"] }
eframe = "0.26.0"
egui = "0.26.0"
rfd = "0.13.0"  # For native file dialogs
image = "0.24.8"  # For image processing